name: Integration Tests & Linting

on: 
  pull_request:
    branches: [main, develop]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps>:
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm install
      - name: Check Linting
        run: npm run lint
      - name: Run tests
        run: npm run test
